<?php

/**
 * BaseAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country
 * @property string $administrative_area_level_1
 * @property string $administrative_area_level_2
 * @property string $administrative_area_level_3
 * @property string $locality
 * @property Doctrine_Collection $Location
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method string              getCountry()                     Returns the current record's "country" value
 * @method string              getAdministrativeAreaLevel1()    Returns the current record's "administrative_area_level_1" value
 * @method string              getAdministrativeAreaLevel2()    Returns the current record's "administrative_area_level_2" value
 * @method string              getAdministrativeAreaLevel3()    Returns the current record's "administrative_area_level_3" value
 * @method string              getLocality()                    Returns the current record's "locality" value
 * @method Doctrine_Collection getLocation()                    Returns the current record's "Location" collection
 * @method Address             setId()                          Sets the current record's "id" value
 * @method Address             setCountry()                     Sets the current record's "country" value
 * @method Address             setAdministrativeAreaLevel1()    Sets the current record's "administrative_area_level_1" value
 * @method Address             setAdministrativeAreaLevel2()    Sets the current record's "administrative_area_level_2" value
 * @method Address             setAdministrativeAreaLevel3()    Sets the current record's "administrative_area_level_3" value
 * @method Address             setLocality()                    Sets the current record's "locality" value
 * @method Address             setLocation()                    Sets the current record's "Location" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('address');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('country', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('administrative_area_level_1', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('administrative_area_level_2', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('administrative_area_level_3', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('locality', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Location', array(
             'local' => 'id',
             'foreign' => 'address_id'));
    }
}