<?php

/**
 * BaseVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $value
 * @property integer $voter
 * @property string $toward
 * @property integer $location_id
 * @property integer $comment_id
 * @property integer $profit_id
 * @property integer $profile_id
 * @property integer $talk_id
 * @property integer $fish_event_id
 * @property sfGuardUserProfile $Voter
 * 
 * @method integer            getValue()         Returns the current record's "value" value
 * @method integer            getVoter()         Returns the current record's "voter" value
 * @method string             getToward()        Returns the current record's "toward" value
 * @method integer            getLocationId()    Returns the current record's "location_id" value
 * @method integer            getCommentId()     Returns the current record's "comment_id" value
 * @method integer            getProfitId()      Returns the current record's "profit_id" value
 * @method integer            getProfileId()     Returns the current record's "profile_id" value
 * @method integer            getTalkId()        Returns the current record's "talk_id" value
 * @method integer            getFishEventId()   Returns the current record's "fish_event_id" value
 * @method sfGuardUserProfile getVoter()         Returns the current record's "Voter" value
 * @method Vote               setValue()         Sets the current record's "value" value
 * @method Vote               setVoter()         Sets the current record's "voter" value
 * @method Vote               setToward()        Sets the current record's "toward" value
 * @method Vote               setLocationId()    Sets the current record's "location_id" value
 * @method Vote               setCommentId()     Sets the current record's "comment_id" value
 * @method Vote               setProfitId()      Sets the current record's "profit_id" value
 * @method Vote               setProfileId()     Sets the current record's "profile_id" value
 * @method Vote               setTalkId()        Sets the current record's "talk_id" value
 * @method Vote               setFishEventId()   Sets the current record's "fish_event_id" value
 * @method Vote               setVoter()         Sets the current record's "Voter" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote');
        $this->hasColumn('value', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('voter', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('toward', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('comment_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('profit_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('talk_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('fish_event_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');

        $this->setSubClasses(array(
             'VoteLocation' => 
             array(
              'toward' => 'location',
             ),
             'VoteComment' => 
             array(
              'toward' => 'comment',
             ),
             'VoteProfit' => 
             array(
              'toward' => 'profit',
             ),
             'VoteProfile' => 
             array(
              'toward' => 'profile',
             ),
             'VoteTalk' => 
             array(
              'toward' => 'talk',
             ),
             'VoteFishEvent' => 
             array(
              'toward' => 'fish_event',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile as Voter', array(
             'local' => 'voter',
             'foreign' => 'id'));
    }
}