<?php

/**
 * BaseBot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property integer $bot_nick_id
 * @property integer $bot_data_id
 * @property sfGuardUserProfile $Profile
 * @property BotNick $BotNick
 * @property BotData $BotData
 * @property Doctrine_Collection $NickMap
 * 
 * @method integer             getProfileId()   Returns the current record's "profile_id" value
 * @method integer             getBotNickId()   Returns the current record's "bot_nick_id" value
 * @method integer             getBotDataId()   Returns the current record's "bot_data_id" value
 * @method sfGuardUserProfile  getProfile()     Returns the current record's "Profile" value
 * @method BotNick             getBotNick()     Returns the current record's "BotNick" value
 * @method BotData             getBotData()     Returns the current record's "BotData" value
 * @method Doctrine_Collection getNickMap()     Returns the current record's "NickMap" collection
 * @method Bot                 setProfileId()   Sets the current record's "profile_id" value
 * @method Bot                 setBotNickId()   Sets the current record's "bot_nick_id" value
 * @method Bot                 setBotDataId()   Sets the current record's "bot_data_id" value
 * @method Bot                 setProfile()     Sets the current record's "Profile" value
 * @method Bot                 setBotNick()     Sets the current record's "BotNick" value
 * @method Bot                 setBotData()     Sets the current record's "BotData" value
 * @method Bot                 setNickMap()     Sets the current record's "NickMap" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bot');
        $this->hasColumn('profile_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('bot_nick_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('bot_data_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile as Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('BotNick', array(
             'local' => 'bot_nick_id',
             'foreign' => 'id'));

        $this->hasOne('BotData', array(
             'local' => 'bot_data_id',
             'foreign' => 'id'));

        $this->hasMany('NickMap', array(
             'local' => 'profile_id',
             'foreign' => 'profile_id'));
    }
}