<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $thumb
 * @property string $toward
 * @property integer $location_id
 * @property integer $profit_id
 * @property Doctrine_Collection $VotePhoto
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getThumb()       Returns the current record's "thumb" value
 * @method string              getToward()      Returns the current record's "toward" value
 * @method integer             getLocationId()  Returns the current record's "location_id" value
 * @method integer             getProfitId()    Returns the current record's "profit_id" value
 * @method Doctrine_Collection getVotePhoto()   Returns the current record's "VotePhoto" collection
 * @method Photo               setId()          Sets the current record's "id" value
 * @method Photo               setName()        Sets the current record's "name" value
 * @method Photo               setThumb()       Sets the current record's "thumb" value
 * @method Photo               setToward()      Sets the current record's "toward" value
 * @method Photo               setLocationId()  Sets the current record's "location_id" value
 * @method Photo               setProfitId()    Sets the current record's "profit_id" value
 * @method Photo               setVotePhoto()   Sets the current record's "VotePhoto" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('thumb', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('toward', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('profit_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');

        $this->setSubClasses(array(
             'PhotoLocation' => 
             array(
              'toward' => 'location',
             ),
             'PhotoProfit' => 
             array(
              'toward' => 'profit',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VotePhoto', array(
             'local' => 'id',
             'foreign' => 'photo_id'));

        $blameable0 = new Doctrine_Template_Blameable(array(
             'listener' => 'BlameableFishery',
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUserProfile',
              'disabled' => false,
              'foreign' => 'id',
              ),
              'updated' => 
              array(
              'class' => 'sfGuardUserProfile',
              'foreign' => 'id',
              'disabled' => false,
              ),
             ),
             'columns' => 
             array(
              'created' => 
              array(
              'length' => 4,
              'type' => 'int',
              ),
              'updated' => 
              array(
              'type' => 'int',
              'length' => 4,
              ),
             ),
             ));
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($blameable0);
        $this->actAs($versionable0);
    }
}