<?php

/**
 * BaseVoteProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property sfGuardUserProfile $sfGuardUserProfile
 * 
 * @method sfGuardUserProfile getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" value
 * @method VoteProfile        setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVoteProfile extends Vote
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));
    }
}