<?php

/**
 * BaseStyle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $ProfitDetail
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getProfitDetail() Returns the current record's "ProfitDetail" collection
 * @method Style               setId()           Sets the current record's "id" value
 * @method Style               setName()         Sets the current record's "name" value
 * @method Style               setProfitDetail() Sets the current record's "ProfitDetail" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStyle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('style');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfitDetail', array(
             'local' => 'id',
             'foreign' => 'style_id'));
    }
}