<?php

/**
 * BaseReadComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property integer $comment_id
 * @property sfGuardUserProfile $sfGuardUserProfile
 * @property Comment $Comment
 * 
 * @method integer            getProfileId()          Returns the current record's "profile_id" value
 * @method integer            getCommentId()          Returns the current record's "comment_id" value
 * @method sfGuardUserProfile getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" value
 * @method Comment            getComment()            Returns the current record's "Comment" value
 * @method ReadComment        setProfileId()          Sets the current record's "profile_id" value
 * @method ReadComment        setCommentId()          Sets the current record's "comment_id" value
 * @method ReadComment        setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" value
 * @method ReadComment        setComment()            Sets the current record's "Comment" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReadComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('read_comment');
        $this->hasColumn('profile_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('comment_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id'));
    }
}