<?php

/**
 * BaseLocationShow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $shows
 * @property integer $location_id
 * @property Location $Location
 * 
 * @method integer      getShows()       Returns the current record's "shows" value
 * @method integer      getLocationId()  Returns the current record's "location_id" value
 * @method Location     getLocation()    Returns the current record's "Location" value
 * @method LocationShow setShows()       Sets the current record's "shows" value
 * @method LocationShow setLocationId()  Sets the current record's "location_id" value
 * @method LocationShow setLocation()    Sets the current record's "Location" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocationShow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location_show');
        $this->hasColumn('shows', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}