<?php

/**
 * BaseProfitFish
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Fish_id
 * @property integer $Profit_id
 * @property float $qty
 * @property Fish $Fish
 * @property Profit $Profit
 * 
 * @method integer    getID()        Returns the current record's "ID" value
 * @method integer    getFishId()    Returns the current record's "Fish_id" value
 * @method integer    getProfitId()  Returns the current record's "Profit_id" value
 * @method float      getQty()       Returns the current record's "qty" value
 * @method Fish       getFish()      Returns the current record's "Fish" value
 * @method Profit     getProfit()    Returns the current record's "Profit" value
 * @method ProfitFish setID()        Sets the current record's "ID" value
 * @method ProfitFish setFishId()    Sets the current record's "Fish_id" value
 * @method ProfitFish setProfitId()  Sets the current record's "Profit_id" value
 * @method ProfitFish setQty()       Sets the current record's "qty" value
 * @method ProfitFish setFish()      Sets the current record's "Fish" value
 * @method ProfitFish setProfit()    Sets the current record's "Profit" value
 * 
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProfitFish extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profit_fish');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('Fish_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Profit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('qty', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Fish', array(
             'local' => 'Fish_id',
             'foreign' => 'id'));

        $this->hasOne('Profit', array(
             'local' => 'Profit_id',
             'foreign' => 'id'));
    }
}