<?php

/**
 * BaseFish
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Profits
 * @property Doctrine_Collection $ProfitFish
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getProfits()    Returns the current record's "Profits" collection
 * @method Doctrine_Collection getProfitFish() Returns the current record's "ProfitFish" collection
 * @method Fish                setId()         Sets the current record's "id" value
 * @method Fish                setName()       Sets the current record's "name" value
 * @method Fish                setProfits()    Sets the current record's "Profits" collection
 * @method Fish                setProfitFish() Sets the current record's "ProfitFish" collection
 * 
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFish extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profit as Profits', array(
             'refClass' => 'ProfitFish',
             'local' => 'Fish_id',
             'foreign' => 'Profit_id'));

        $this->hasMany('ProfitFish', array(
             'local' => 'id',
             'foreign' => 'Fish_id'));
    }
}