<?php

/**
 * BaseInbox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $message
 * @property integer $profile_id
 * @property Profile $Profile
 * @property Doctrine_Collection $Inboxed
 * @property Doctrine_Collection $CommentInbox
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getMessage()      Returns the current record's "message" value
 * @method integer             getProfileId()    Returns the current record's "profile_id" value
 * @method Profile             getProfile()      Returns the current record's "Profile" value
 * @method Doctrine_Collection getInboxed()      Returns the current record's "Inboxed" collection
 * @method Doctrine_Collection getCommentInbox() Returns the current record's "CommentInbox" collection
 * @method Inbox               setId()           Sets the current record's "id" value
 * @method Inbox               setName()         Sets the current record's "name" value
 * @method Inbox               setMessage()      Sets the current record's "message" value
 * @method Inbox               setProfileId()    Sets the current record's "profile_id" value
 * @method Inbox               setProfile()      Sets the current record's "Profile" value
 * @method Inbox               setInboxed()      Sets the current record's "Inboxed" collection
 * @method Inbox               setCommentInbox() Sets the current record's "CommentInbox" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInbox extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inbox');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasMany('Profile as Inboxed', array(
             'refClass' => 'Inboxed',
             'local' => 'inbox_id',
             'foreign' => 'profile_id'));

        $this->hasMany('CommentInbox', array(
             'local' => 'id',
             'foreign' => 'inbox_id'));
    }
}