<?php

/**
 * BaseNickMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property string $nick
 * @property IsBot $Bot
 * 
 * @method integer getProfileId()  Returns the current record's "profile_id" value
 * @method string  getNick()       Returns the current record's "nick" value
 * @method IsBot   getBot()        Returns the current record's "Bot" value
 * @method NickMap setProfileId()  Sets the current record's "profile_id" value
 * @method NickMap setNick()       Sets the current record's "nick" value
 * @method NickMap setBot()        Sets the current record's "Bot" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNickMap extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nick_map');
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('nick', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IsBot as Bot', array(
             'local' => 'profile_id',
             'foreign' => 'profile_id',
             'onDelete' => 'cascade'));
    }
}