<?php

/**
 * BasePoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $route_id
 * @property Route $Route
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6485 2009-10-12 18:41:59Z jwage $
 */
abstract class BasePoint extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('point');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('route_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Route', array(
             'local' => 'route_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $geographical0 = new Doctrine_Template_Geographical(array(
             'fields' => 
             array(
              0 => 'lat',
              1 => 'lng',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($geographical0);
        $this->actAs($timestampable0);
    }
}