<?php

/**
 * BaseProfit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $Location_id
 * @property integer $Profile_id
 * @property time $time
 * @property string $description
 * @property Location $Location
 * @property Profile $Profile
 * @property Doctrine_Collection $Fishes
 * @property Doctrine_Collection $Styles
 * @property Doctrine_Collection $ProfitFish
 * @property Doctrine_Collection $ProfitSyle
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getLocationId()  Returns the current record's "Location_id" value
 * @method integer             getProfileId()   Returns the current record's "Profile_id" value
 * @method time                getTime()        Returns the current record's "time" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Location            getLocation()    Returns the current record's "Location" value
 * @method Profile             getProfile()     Returns the current record's "Profile" value
 * @method Doctrine_Collection getFishes()      Returns the current record's "Fishes" collection
 * @method Doctrine_Collection getStyles()      Returns the current record's "Styles" collection
 * @method Doctrine_Collection getProfitFish()  Returns the current record's "ProfitFish" collection
 * @method Doctrine_Collection getProfitSyle()  Returns the current record's "ProfitSyle" collection
 * @method Profit              setId()          Sets the current record's "id" value
 * @method Profit              setLocationId()  Sets the current record's "Location_id" value
 * @method Profit              setProfileId()   Sets the current record's "Profile_id" value
 * @method Profit              setTime()        Sets the current record's "time" value
 * @method Profit              setDescription() Sets the current record's "description" value
 * @method Profit              setLocation()    Sets the current record's "Location" value
 * @method Profit              setProfile()     Sets the current record's "Profile" value
 * @method Profit              setFishes()      Sets the current record's "Fishes" collection
 * @method Profit              setStyles()      Sets the current record's "Styles" collection
 * @method Profit              setProfitFish()  Sets the current record's "ProfitFish" collection
 * @method Profit              setProfitSyle()  Sets the current record's "ProfitSyle" collection
 * 
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProfit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profit');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Location_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('Profile_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'Location_id',
             'foreign' => 'id'));

        $this->hasOne('Profile', array(
             'local' => 'Profile_id',
             'foreign' => 'id'));

        $this->hasMany('Fish as Fishes', array(
             'refClass' => 'ProfitFish',
             'local' => 'Profit_id',
             'foreign' => 'Fish_id'));

        $this->hasMany('Style as Styles', array(
             'refClass' => 'ProfitSyle',
             'local' => 'Profit_id',
             'foreign' => 'Style_id'));

        $this->hasMany('ProfitFish', array(
             'local' => 'id',
             'foreign' => 'Profit_id'));

        $this->hasMany('ProfitSyle', array(
             'local' => 'id',
             'foreign' => 'Profit_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}