<?php

/**
 * BaseFriend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $source_profile_id
 * @property integer $related_profile_id
 * @property Profile $Profile
 * 
 * @method integer getId()                 Returns the current record's "id" value
 * @method integer getSourceProfileId()    Returns the current record's "source_profile_id" value
 * @method integer getRelatedProfileId()   Returns the current record's "related_profile_id" value
 * @method Profile getProfile()            Returns the current record's "Profile" value
 * @method Friend  setId()                 Sets the current record's "id" value
 * @method Friend  setSourceProfileId()    Sets the current record's "source_profile_id" value
 * @method Friend  setRelatedProfileId()   Sets the current record's "related_profile_id" value
 * @method Friend  setProfile()            Sets the current record's "Profile" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFriend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friend');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('source_profile_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('related_profile_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'source_profile_id',
             'foreign' => 'id'));
    }
}