<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nick_name
 * @property string $first_name
 * @property string $last_name
 * @property string $description
 * @property Doctrine_Collection $Profit
 * @property Doctrine_Collection $Friend
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNickName()    Returns the current record's "nick_name" value
 * @method string              getFirstName()   Returns the current record's "first_name" value
 * @method string              getLastName()    Returns the current record's "last_name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getProfit()      Returns the current record's "Profit" collection
 * @method Doctrine_Collection getFriend()      Returns the current record's "Friend" collection
 * @method Profile             setId()          Sets the current record's "id" value
 * @method Profile             setNickName()    Sets the current record's "nick_name" value
 * @method Profile             setFirstName()   Sets the current record's "first_name" value
 * @method Profile             setLastName()    Sets the current record's "last_name" value
 * @method Profile             setDescription() Sets the current record's "description" value
 * @method Profile             setProfit()      Sets the current record's "Profit" collection
 * @method Profile             setFriend()      Sets the current record's "Friend" collection
 * 
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('nick_name', 'string', 50, array(
             'default' => '',
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('first_name', 'string', 50, array(
             'default' => '',
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'default' => '',
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('description', 'string', null, array(
             'default' => '',
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profit', array(
             'local' => 'id',
             'foreign' => 'Profile_id'));

        $this->hasMany('Friend', array(
             'local' => 'id',
             'foreign' => 'related_Profile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}