<?php

/**
 * BaseVoteComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Comment $Comment
 * 
 * @method Comment     getComment() Returns the current record's "Comment" value
 * @method VoteComment setComment() Sets the current record's "Comment" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVoteComment extends Vote
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id'));
    }
}