<?php

/**
 * BaseVoteLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Location $Location
 * 
 * @method Location     getLocation() Returns the current record's "Location" value
 * @method VoteLocation setLocation() Sets the current record's "Location" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVoteLocation extends Vote
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id'));
    }
}