<?php

/**
 * BaseRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Points
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6485 2009-10-12 18:41:59Z jwage $
 */
abstract class BaseRoute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('route');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => '',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Point as Points', array(
             'local' => 'id',
             'foreign' => 'route_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}