<?php

/**
 * BaseBotData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $uid
 * @property string $name
 * @property string $ava
 * @property string $userpic
 * @property Doctrine_Collection $Bot
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method integer             getUid()     Returns the current record's "uid" value
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getAva()     Returns the current record's "ava" value
 * @method string              getUserpic() Returns the current record's "userpic" value
 * @method Doctrine_Collection getBot()     Returns the current record's "Bot" collection
 * @method BotData             setId()      Sets the current record's "id" value
 * @method BotData             setUid()     Sets the current record's "uid" value
 * @method BotData             setName()    Sets the current record's "name" value
 * @method BotData             setAva()     Sets the current record's "ava" value
 * @method BotData             setUserpic() Sets the current record's "userpic" value
 * @method BotData             setBot()     Sets the current record's "Bot" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBotData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bot_data');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('uid', 'integer', 4, array(
             'unique' => true,
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ava', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('userpic', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bot', array(
             'local' => 'id',
             'foreign' => 'bot_data_id'));
    }
}