<?php

/**
 * BaseCommentProfit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Profit $Profit
 * 
 * @method Profit        getProfit() Returns the current record's "Profit" value
 * @method CommentProfit setProfit() Sets the current record's "Profit" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentProfit extends Comment
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profit', array(
             'local' => 'profit_id',
             'foreign' => 'id'));
    }
}