<?php

/**
 * BaseAreaHigh
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $area_low_id
 * @property AreaLow $AreaLow
 * @property Doctrine_Collection $Address
 * @property Doctrine_Collection $Locality
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getAreaLowId()   Returns the current record's "area_low_id" value
 * @method AreaLow             getAreaLow()     Returns the current record's "AreaLow" value
 * @method Doctrine_Collection getAddress()     Returns the current record's "Address" collection
 * @method Doctrine_Collection getLocality()    Returns the current record's "Locality" collection
 * @method AreaHigh            setId()          Sets the current record's "id" value
 * @method AreaHigh            setName()        Sets the current record's "name" value
 * @method AreaHigh            setAreaLowId()   Sets the current record's "area_low_id" value
 * @method AreaHigh            setAreaLow()     Sets the current record's "AreaLow" value
 * @method AreaHigh            setAddress()     Sets the current record's "Address" collection
 * @method AreaHigh            setLocality()    Sets the current record's "Locality" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAreaHigh extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area_high');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('area_low_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AreaLow', array(
             'local' => 'area_low_id',
             'foreign' => 'id'));

        $this->hasMany('Address', array(
             'local' => 'id',
             'foreign' => 'area_high_id'));

        $this->hasMany('Locality', array(
             'local' => 'id',
             'foreign' => 'area_high_id'));
    }
}