<?php

/**
 * BaseProfit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $location_id
 * @property date $date
 * @property string $cordage
 * @property string $description
 * @property float $best_weight
 * @property integer $best_fish_id
 * @property Location $Location
 * @property Fish $Fish
 * @property Doctrine_Collection $ProfitDetail
 * @property Doctrine_Collection $CommentProfit
 * @property Doctrine_Collection $VoteProfit
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getLocationId()    Returns the current record's "location_id" value
 * @method date                getDate()          Returns the current record's "date" value
 * @method string              getCordage()       Returns the current record's "cordage" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method float               getBestWeight()    Returns the current record's "best_weight" value
 * @method integer             getBestFishId()    Returns the current record's "best_fish_id" value
 * @method Location            getLocation()      Returns the current record's "Location" value
 * @method Fish                getFish()          Returns the current record's "Fish" value
 * @method Doctrine_Collection getProfitDetail()  Returns the current record's "ProfitDetail" collection
 * @method Doctrine_Collection getCommentProfit() Returns the current record's "CommentProfit" collection
 * @method Doctrine_Collection getVoteProfit()    Returns the current record's "VoteProfit" collection
 * @method Profit              setId()            Sets the current record's "id" value
 * @method Profit              setLocationId()    Sets the current record's "location_id" value
 * @method Profit              setDate()          Sets the current record's "date" value
 * @method Profit              setCordage()       Sets the current record's "cordage" value
 * @method Profit              setDescription()   Sets the current record's "description" value
 * @method Profit              setBestWeight()    Sets the current record's "best_weight" value
 * @method Profit              setBestFishId()    Sets the current record's "best_fish_id" value
 * @method Profit              setLocation()      Sets the current record's "Location" value
 * @method Profit              setFish()          Sets the current record's "Fish" value
 * @method Profit              setProfitDetail()  Sets the current record's "ProfitDetail" collection
 * @method Profit              setCommentProfit() Sets the current record's "CommentProfit" collection
 * @method Profit              setVoteProfit()    Sets the current record's "VoteProfit" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProfit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profit');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('cordage', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('best_weight', 'float', 10, array(
             'type' => 'float',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('best_fish_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id'));

        $this->hasOne('Fish', array(
             'local' => 'best_fish_id',
             'foreign' => 'id'));

        $this->hasMany('ProfitDetail', array(
             'local' => 'id',
             'foreign' => 'profit_id'));

        $this->hasMany('CommentProfit', array(
             'local' => 'id',
             'foreign' => 'profit_id'));

        $this->hasMany('VoteProfit', array(
             'local' => 'id',
             'foreign' => 'profit_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'listener' => 'BlameableFishery',
             'columns' => 
             array(
              'created' => 
              array(
              'length' => 4,
              'type' => 'int',
              ),
              'updated' => 
              array(
              'length' => 4,
              'type' => 'int',
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'Profile',
              'disabled' => false,
              'foreign' => 'id',
              ),
              'updated' => 
              array(
              'foreign' => 'id',
              'disabled' => false,
              'class' => 'Profile',
              ),
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
    }
}