<?php

/**
 * BaseCommentLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Location $Location
 * 
 * @method Location        getLocation() Returns the current record's "Location" value
 * @method CommentLocation setLocation() Sets the current record's "Location" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommentLocation extends Comment
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id'));
    }
}