<?php

/**
 * BaseTalkSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $parent
 * @property Doctrine_Collection $Talk
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method integer             getParent() Returns the current record's "parent" value
 * @method Doctrine_Collection getTalk()   Returns the current record's "Talk" collection
 * @method TalkSection         setId()     Sets the current record's "id" value
 * @method TalkSection         setName()   Sets the current record's "name" value
 * @method TalkSection         setParent() Sets the current record's "parent" value
 * @method TalkSection         setTalk()   Sets the current record's "Talk" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTalkSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('talk_section');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('parent', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Talk', array(
             'local' => 'id',
             'foreign' => 'talk_section_id'));
    }
}