<?php

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $region_id
 * @property integer $weight
 * @property Region $Region
 * @property Doctrine_Collection $sfGuardUserProfile
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method integer             getRegionId()           Returns the current record's "region_id" value
 * @method integer             getWeight()             Returns the current record's "weight" value
 * @method Region              getRegion()             Returns the current record's "Region" value
 * @method Doctrine_Collection getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" collection
 * @method City                setId()                 Sets the current record's "id" value
 * @method City                setName()               Sets the current record's "name" value
 * @method City                setRegionId()           Sets the current record's "region_id" value
 * @method City                setWeight()             Sets the current record's "weight" value
 * @method City                setRegion()             Sets the current record's "Region" value
 * @method City                setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('region_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('weight', 'integer', 4, array(
             'default' => 0,
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'city_id'));
    }
}