<?php

/**
 * BaseFishEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property string $name
 * @property string $description
 * @property string $rules
 * @property integer $location_id
 * @property Location $Location
 * @property Doctrine_Collection $VoteFishEvent
 * @property Doctrine_Collection $CommentFishEvent
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method date                getDate()             Returns the current record's "date" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method string              getRules()            Returns the current record's "rules" value
 * @method integer             getLocationId()       Returns the current record's "location_id" value
 * @method Location            getLocation()         Returns the current record's "Location" value
 * @method Doctrine_Collection getVoteFishEvent()    Returns the current record's "VoteFishEvent" collection
 * @method Doctrine_Collection getCommentFishEvent() Returns the current record's "CommentFishEvent" collection
 * @method FishEvent           setId()               Sets the current record's "id" value
 * @method FishEvent           setDate()             Sets the current record's "date" value
 * @method FishEvent           setName()             Sets the current record's "name" value
 * @method FishEvent           setDescription()      Sets the current record's "description" value
 * @method FishEvent           setRules()            Sets the current record's "rules" value
 * @method FishEvent           setLocationId()       Sets the current record's "location_id" value
 * @method FishEvent           setLocation()         Sets the current record's "Location" value
 * @method FishEvent           setVoteFishEvent()    Sets the current record's "VoteFishEvent" collection
 * @method FishEvent           setCommentFishEvent() Sets the current record's "CommentFishEvent" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFishEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_event');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('rules', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id'));

        $this->hasMany('VoteFishEvent', array(
             'local' => 'id',
             'foreign' => 'fish_event_id'));

        $this->hasMany('CommentFishEvent', array(
             'local' => 'id',
             'foreign' => 'fish_event_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'listener' => 'BlameableFishery',
             'columns' => 
             array(
              'created' => 
              array(
              'type' => 'int',
              'length' => 4,
              ),
              'updated' => 
              array(
              'type' => 'int',
              'length' => 4,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'disabled' => false,
              'class' => 'sfGuardUserProfile',
              'foreign' => 'id',
              ),
              'updated' => 
              array(
              'disabled' => false,
              'class' => 'sfGuardUserProfile',
              'foreign' => 'id',
              ),
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
    }
}