<?php

/**
 * BaseVotePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Photo $Photo
 * 
 * @method Photo     getPhoto() Returns the current record's "Photo" value
 * @method VotePhoto setPhoto() Sets the current record's "Photo" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVotePhoto extends Vote
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Photo', array(
             'local' => 'photo_id',
             'foreign' => 'id'));
    }
}