<?php

/**
 * BaseTalkSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent
 * @property string $name
 * @property Doctrine_Collection $Talk
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method integer             getParent() Returns the current record's "parent" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getTalk()   Returns the current record's "Talk" collection
 * @method TalkSection         setId()     Sets the current record's "id" value
 * @method TalkSection         setParent() Sets the current record's "parent" value
 * @method TalkSection         setName()   Sets the current record's "name" value
 * @method TalkSection         setTalk()   Sets the current record's "Talk" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTalkSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('talk_section');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Talk', array(
             'local' => 'id',
             'foreign' => 'talk_section_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => false,
             ));
        $this->actAs($nestedset0);
    }
}