<?php

/**
 * BaseFish
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $ProfitDetail
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getProfitDetail() Returns the current record's "ProfitDetail" collection
 * @method Fish                setId()           Sets the current record's "id" value
 * @method Fish                setName()         Sets the current record's "name" value
 * @method Fish                setProfitDetail() Sets the current record's "ProfitDetail" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFish extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfitDetail', array(
             'local' => 'id',
             'foreign' => 'fish_id'));
    }
}