<?php

/**
 * BaseVoteProfit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Profit $Profit
 * 
 * @method Profit     getProfit() Returns the current record's "Profit" value
 * @method VoteProfit setProfit() Sets the current record's "Profit" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVoteProfit extends Vote
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profit', array(
             'local' => 'profit_id',
             'foreign' => 'id'));
    }
}