<?php

/**
 * BaseProfitSyle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Style_id
 * @property integer $Profit_id
 * @property Style $Style
 * @property Profit $Profit
 * 
 * @method integer    getID()        Returns the current record's "ID" value
 * @method integer    getStyleId()   Returns the current record's "Style_id" value
 * @method integer    getProfitId()  Returns the current record's "Profit_id" value
 * @method Style      getStyle()     Returns the current record's "Style" value
 * @method Profit     getProfit()    Returns the current record's "Profit" value
 * @method ProfitSyle setID()        Sets the current record's "ID" value
 * @method ProfitSyle setStyleId()   Sets the current record's "Style_id" value
 * @method ProfitSyle setProfitId()  Sets the current record's "Profit_id" value
 * @method ProfitSyle setStyle()     Sets the current record's "Style" value
 * @method ProfitSyle setProfit()    Sets the current record's "Profit" value
 * 
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProfitSyle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profit_syle');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('Style_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Profit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Style', array(
             'local' => 'Style_id',
             'foreign' => 'id'));

        $this->hasOne('Profit', array(
             'local' => 'Profit_id',
             'foreign' => 'id'));
    }
}