<?php

/**
 * BaseReadComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property integer $comment_id
 * @property Profile $Profile
 * @property Comment $Comment
 * 
 * @method integer     getProfileId()  Returns the current record's "profile_id" value
 * @method integer     getCommentId()  Returns the current record's "comment_id" value
 * @method Profile     getProfile()    Returns the current record's "Profile" value
 * @method Comment     getComment()    Returns the current record's "Comment" value
 * @method ReadComment setProfileId()  Sets the current record's "profile_id" value
 * @method ReadComment setCommentId()  Sets the current record's "comment_id" value
 * @method ReadComment setProfile()    Sets the current record's "Profile" value
 * @method ReadComment setComment()    Sets the current record's "Comment" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseReadComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('read_comment');
        $this->hasColumn('profile_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('comment_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id'));
    }
}