<?php

/**
 * BaseFishEventType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $weight
 * @property Doctrine_Collection $FishEvent
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getWeight()    Returns the current record's "weight" value
 * @method Doctrine_Collection getFishEvent() Returns the current record's "FishEvent" collection
 * @method FishEventType       setId()        Sets the current record's "id" value
 * @method FishEventType       setName()      Sets the current record's "name" value
 * @method FishEventType       setWeight()    Sets the current record's "weight" value
 * @method FishEventType       setFishEvent() Sets the current record's "FishEvent" collection
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Sergei Belov <limitium@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishEventType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_event_type');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FishEvent', array(
             'local' => 'id',
             'foreign' => 'fish_event_type_id'));
    }
}