<?php

/**
 * BaseLocationSeason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $location_id
 * @property integer $season_id
 * @property Location $Location
 * @property Season $Season
 * 
 * @method integer        getLocationId()  Returns the current record's "location_id" value
 * @method integer        getSeasonId()    Returns the current record's "season_id" value
 * @method Location       getLocation()    Returns the current record's "Location" value
 * @method Season         getSeason()      Returns the current record's "Season" value
 * @method LocationSeason setLocationId()  Sets the current record's "location_id" value
 * @method LocationSeason setSeasonId()    Sets the current record's "season_id" value
 * @method LocationSeason setLocation()    Sets the current record's "Location" value
 * @method LocationSeason setSeason()      Sets the current record's "Season" value
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLocationSeason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location_season');
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('season_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id'));

        $this->hasOne('Season', array(
             'local' => 'season_id',
             'foreign' => 'id'));
    }
}