<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/09 22:16:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=HT',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
