<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/10/21 00:57:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=HT',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
