<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/10/21 18:23:38
sfConfig::add(array(
  'app_map_key' => 'ABQIAAAA8wGhpYTzhzuU6t9zcf0f9RTRkADJtHLtgosa3gIacxHGEJbD2RS6P-Ki8BWqPluPZtn1FirDTUhAAw',
));
