<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/09 22:16:25
sfConfig::add(array(
  'app_map_key' => 'ABQIAAAA8wGhpYTzhzuU6t9zcf0f9RTRkADJtHLtgosa3gIacxHGEJbD2RS6P-Ki8BWqPluPZtn1FirDTUhAAw',
));
