<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2009/10/21 00:57:35
return array(

  // sfDoctrinePlugin_module_libs

  // project
  'baseform' => 'Z:/home/HT/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => 'Z:/home/HT/apps/frontend/lib/myUser.class.php',

  // modules

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrinedataretriever' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDataRetriever.class.php',
  'sfwebdebugpaneldoctrine' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrinelogger' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/log/sfDoctrineLogger.class.php',
  'swift_doctrinespool' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecordlistener' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordListener.class.php',
  'sfdoctrineroute' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildallloadtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllLoadTask.class.php',
  'sfdoctrinebuildallreloadtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTask.class.php',
  'sfdoctrinebuildallreloadtestalltask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTestAllTask.class.php',
  'sfdoctrinebuildalltask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllTask.class.php',
  'sfdoctrinebuilddbtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinerebuilddbtask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineRebuildDbTask.class.php',
  'sfdoctrinereloaddatatask' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineReloadDataTask.class.php',
  'sftesterdoctrine' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrineuniquevalidator' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/validator/sfDoctrineUniqueValidator.class.php',
  'sfvalidatordoctrinechoice' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrinechoicemany' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoiceMany.class.php',
  'sfvalidatordoctrineunique' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfwidgetformdoctrinechoicemany' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoiceMany.class.php',
  'sfwidgetformdoctrineselect' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelect.class.php',
  'sfwidgetformdoctrineselectmany' => 'D:/WebServers/symfony-1.3.0ALPHA2/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelectMany.class.php',
);
