<?php

/**
 * BotDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BotData');
    }
}