<?php

/**
 * BotNickTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotNickTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotNickTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BotNick');
    }
}