<?php

/**
 * FishEventTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FishEventTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FishEventTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FishEventType');
    }
}