<?php

/**
 * IsBotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IsBotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IsBotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IsBot');
    }
}