<?php

/**
 * NickMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NickMapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NickMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NickMap');
    }
}