<?php

/**
 * PhotoProfitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoProfitTable extends PhotoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoProfitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoProfit');
    }
}