<?php

/**
 * Profile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Profile extends BaseProfile {

    public function setTableDefinition() {
        parent:: setTableDefinition();

        $this->hasColumn('user_id', 'integer', 4, array(
            'type' => 'integer',
            'length' => '4',
        ));
    }
    public function setUp() {
        parent::setUp();

        $this->hasOne('sfGuardUser', array(
            'local' => 'user_id',
            'foreign' => 'id',
        ));
    }

    public function getRating() {
        $rating = intval(Doctrine_Query::create()
            ->select('SUM(v.value) as rating')
            ->from('VoteProfile v')
            ->where('v.profile_id = ?',$this->getId())
            ->execute()
            ->getFirst()
            ->getRating());
        return $rating?$rating:0;
    }

    public function getForce($rating = null) {
        if($rating == null) {
            $rating = $this->getRating();
        }
        if($rating < 99) {
            return 1;
        }
        if($rating<249) {
            return 2;
        }
        if($rating<499) {
            return 3;
        }
        if($rating<749) {
            return 4;
        }
        if($rating<999) {
            return 5;
        }
        if($rating<1499) {
            return 6;
        }
        if($rating<1999) {
            return 7;
        }
        return 8;
    }
}