<?php

/**
 * Route
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    HT
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6485 2009-10-12 18:41:59Z jwage $
 */
class Route extends BaseRoute {
    public function getEncodedPoints() {
        $encoded =  array();
        foreach($this->getPoints() as $point) {
            $encoded[]=$point->getLatitude().';'.$point->getLongitude();
        }
        return implode('|',$encoded);
    }
}