<?php

/**
 * Talk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Talk extends BaseTalk {

    public $plused = false;
    public $minused = false;

    public function getRating() {
        return Vote::getRating($this);
    }

    public function setUp() {
        parent::setUp();

        $this->hasMany('Tagging', array(
            'local' => 'id',
            'foreign' => 'taggable_id'));
    }

    public function getSections() {
        $sections = array($this->getTalkSection());
        foreach ($this->getTalkSection()->getNode()->getAncestors() as $section) {
            if (!$section->getNode()->isRoot()) {
                $sections[] = $section;
            }
        }
        return array_reverse($sections);
    }

    public static function getPager(Doctrine_Query $query, $url, $curPage = 1) {
        $pagerLayout = new htPagerLayout(
                        new Doctrine_Pager(
                                $query,
                                $curPage,
                                5
                        ),
                        new Doctrine_Pager_Range_Sliding(array(
                            'chunk' => 10
                        )),
                        $url
        );

        $pagerLayout->setTemplate('{link_to}{%page}{/link_to}');
        $pagerLayout->setSelectedTemplate('<span>{%page}</span>');
        return $pagerLayout;
    }

}