<?php

/**
 * Talk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Talk extends BaseTalk {

    public $plused = false;
    public $minused = false;

    public function getRating() {
        return Vote::getRating($this);
    }

    public function setUp() {
        parent::setUp();

        $this->hasMany('Tagging', array(
            'local' => 'id',
            'foreign' => 'taggable_id'));
    }

    public function getSections() {
        $sections = array($this->getTalkSection());
        foreach ($this->getTalkSection()->getNode()->getAncestors() as $section) {
            if (!$section->getNode()->isRoot()) {
                $sections[] = $section;
            }
        }
        return array_reverse($sections);
    }

    public function save(Doctrine_Connection $conn = null) {

        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try {
            $ret = parent::save($conn);

            LuceneEngine::updateLuceneIndexFor($this);

            $conn->commit();

            return $ret;
        } catch (Exception $e) {
            $conn->rollBack();
            throw $e;
        }
    }

    public function delete(Doctrine_Connection $conn = null) {
        LuceneEngine::deleteLuceneIndexFor($this);
        return parent::delete($conn);
    }

}