<?php

/**
 * VotePhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VotePhotoTable extends VoteTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VotePhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VotePhoto');
    }
}