all:
  sf_guard_plugin:
    algorithm_callable: [PasswordKeeper, generate]
    signin_form: FloginForm
    remember_cookie_name: ht_remember
    routes_register: false
    success_signout_url: "@homepage"
    
  sfForkedApply:
    applyForm: FRegistrationForm
    mail_editable: true
    confirmation:
      reset: false
      apply: false
      email: true
      reset_logged: false
    
  sfApplyPlugin:
    apply:
      subject: "Подтверждение аккаунта на uberlov.ru"
    from:
      email: "mailer@uberlov.ru"
      fullname: "Uberlov"
      routes:
          apply: /register
          reset: /password-reset
          resetRequest: /reset-request
          resetCancel: /reset-cancel
          validate: /user/confirm/:validate
          settings: /settings
  sf_jquery_form_validation:
    default: disabled
#    forms: [FloginForm, FRegistrationForm]
