all:
  sf_guard_plugin:
    algorithm_callable: [PasswordKeeper, generate]
    signin_form: FloginForm
    remember_cookie_name: ht_remember
    routes_register: false
    
  sfForkedApply:
    applyForm: FRegistrationForm
    mail_editable: true
    
  sfApplyPlugin:
    apply:
      subject: "Подтверждение аккаунта на %1%"
    from:
      email: "spamer@uberlov.ru"
      fullname: "Важная информация с www.uberlov.ru"
      routes:
          apply: /register
          reset: /password-reset
          resetRequest: /reset-request
          resetCancel: /reset-cancel
          validate: /user/confirm/:validate
          settings: /settings

