# default rules
homepage:
  url:   /
  param: { module: default, action: underconstruction}  

#main routes
map:
  url: /map
  param: {module: collector, action locations, menu map}  
regions:
  url: /regions
  param: {module: collector, action regions, menu regions}  
profits:
  url: /profits
  param: {module: profit, action list, menu profits}
talks:
  url: /talks
  param: {module: talk, action list, menu talks}
events:
  url: /events
  param: {module: event, action list, menu events}
people:
  url: /people
  param: {module: profile, action list, menu people}
    

#guard routes
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin, menu sf_guard_signin}

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

#apply
user_confirm:
  url:          /user/confirm/:validate
  param:        { module: sfApply, action: confirm}
  
#profile routes
friends:
  url:   /friends
  param: { module: profile, action: friends, menu friends }
inboxes:
  url:   /inboxes
  param: { module: inbox, action: list, menu inboxes}
my_locations:
  url:   /my_locations
  param: { module: location, action: my, menu my_locations}
my_profile:
  url:   /my_profile
  param: { module: profile, action: my, menu my_profile}
  
#to remove nah!
  default:
  url:   /:module/:action/*
