# default rules
homepage:
  url:   /
  param: { module: default, action: underconstruction }

default:
  url:   /:module/:action/*

user_confirm:
  url:          /user/confirm/:validate
  param:        { module: sfApply, action: confirm}
