default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    description:  symfony project
    keywords:     symfony, project
    language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    [lib/jquery-1.4.2.js,lib/jqueryBlockUI,lib/jqueryColor,lib/jqueryJSON,moduleManager]

  has_layout:     true
  layout:         layout
