default:
  http_metas:
    content-type: text/html

  metas:
    title:        Uberlov
    description:  карта рыбных мест, рыбные места, рыбаловные места, рыбалка, места ловли
    keywords:     карта, рыбалка, места, ловля
    language:     ru
    robots:       index, follow

  stylesheets:    [reset,base,header,menu,main,footer,button,common, form, location, comment, profile,rating,profit,user,inbox,talk,pager,address,event,lib/datepicker,lib/redactor/redactor]

  javascripts:    [lib/jquery-1.4.2.js,lib/jqueryBlockUI,lib/jqueryColor,lib/jqueryJSON,lib/datepicker,lib/redactor/redactor,app,moduleManager]

  has_layout:     true
  layout:         layout
