default:
  http_metas:
    content-type: text/html

  metas:
    title:        uberЛОВ
    description:  карта рыбных мест, рыбные места, рыбаловные места, рыбалка, места ловли
    keywords:     карта, рыбалка, места, ловля
    language:     ru
    robots:       index, follow

  stylesheets:    [reset,base,header,menu,main,footer,button, location,comment,profile,rating,profit,user,inbox,talk,pager,address,lib/datepicker]

  javascripts:    [lib/jquery-1.4.2.js,lib/jqueryBlockUI,lib/jqueryColor,lib/jqueryJSON,lib/datepicker,lib/tinymce/jquery.tinymce.js,app,moduleManager]

  has_layout:     true
  layout:         layout
