<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    FISHERY
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {
    public function setUp() {
        parent::setUp();
        
        $this->hasOne('sfGuardUserProfile as Profile', array(
            'local' => 'id',
            'foreign' => 'user_id'));
    }
}