all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=FISHERY
      username: root
      password:
      encoding: utf8
      collate: utf8_unicode_ci
      charset: utf8
