<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/06 18:53:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=HT',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
