<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/31 21:05:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=FISHERY',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
