<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/10/24 19:35:52
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
