Bot:
  columns:
    profile_id:
      primary: true
      type: integer(4)
    bot_nick_id:
      type: integer(4)
    bot_data_id:
      type: integer(4)
  relations:
    Profile:
      class: sfGuardUserProfile
      onDelete: cascade
      local: profile_id
      foreign: id
    BotNick:
      local: bot_nick_id
      foreign: id
    BotData:
      local: bot_data_id
      foreign: id
NickMap:
  columns:
    profile_id:
      type: integer(4)
      notnull: true
    nick:
      type: string(255)
  relations:
    Bot:
      class: Bot
      onDelete: cascade
      local: profile_id
      foreign: profile_id
BotNick:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    nick:
      unique: true
      type: string(255)
      notnull: true
BotData:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    uid:
      unique: true
      type: integer(4)
      notnull: true
    name:
      type: string(255)
    ava:
      type: string(255)
    userpic:
      type: string(255)