Location:
  tableName: location
  actAs:
    Blameable:
      listener: BlameableFishery
    Geographical: 
    Sluggable: 
    Timestampable: 
    Versionable: 
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      default: ''
      type: string(50)
      notnull: true
    description:
      default: ''
      type: string
      notnull: true
    depth:
      type: float
    location_flow_id:
      type: integer(4)
    location_fundus_id:
      type: integer(4)
    location_relief_id:
      type: integer(4)
  relations:
    LocationFlow:
      local: location_flow_id
      foreign: id
    LocationFundus:
      local: location_fundus_id
      foreign: id
    LocationRelief:
      local: location_relief_id
      foreign: id
Profile:
  tableName: profile
  actAs:
    Timestampable: 
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    nick_name:
      default: ''
      type: string(50)
      notnull: true
    first_name:
      default: ''
      type: string(50)
    last_name:
      default: ''
      type: string(50)
    description:
      default: ''
      type: string
      notnull: true
Fish:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    name:
      unique: true
      type: string(100)
      notnull: true
Profit:
  actAs:
    Timestampable: 
    Blameable:
      listener: BlameableFishery
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    location_id:
      type: integer(4)
    begin:
      type: timestamp
      notnull: true
    water_state:
      type: string
    lure:
      type: string
    bait:
      type: string
    additive:
      type: string
    weather:
      type: string
    cordage:
      type: string
    description:
      type: string
      notnull: true
  relations:
    Location:
      local: location_id
      foreign: id
Style:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    name:
      unique: true
      type: string(100)
      notnull: true
Friend:
  columns:
    id:
      primary: true
      unique: true
      type: integer
      notnull: true
    source_profile_id:
      type: integer
      notnull: true
    related_profile_id:
      type: integer
      notnull: true
  relations:
    Profile:
      local: source_profile_id
      foreign: id
ProfitDetail:
  columns:
    time:
      type: timestamp
      notnull: true
    profit_id:
      type: integer
    style_id:
      type: integer
    fish_id:
      type: integer
    qty:
      type: float
      notnull: true
  indexes:
    unique_fish_style_per_profit:
      fields: [profit_id, style_id, fish_id]
      type: unique
  relations:
    Profit:
      local: profit_id
      foreign: id
    Style:
      local: style_id
      foreign: id
    Fish:
      local: fish_id
      foreign: id
LocationRelief:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(50)
      notnull: true
LocationFlow:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(50)
      notnull: true
LocationFundus:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(50)
      notnull: true
Comment:
  actAs:
    NestedSet:
      hasManyRoots: true
    Timestampable: 
    Blameable:
      listener: BlameableFishery
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    message:
      type: string(1000)
      notnull: true
CommentLocation:
  inheritance:
    extends: Comment
    type: column_aggregation
    keyField: toward
    keyValue: location
  columns:
    location_id:
      type: integer(4)
  relations:
    Location:
      local: location_id
      foreign: id
CommentProfit:
  inheritance:
    extends: Comment
    keyField: toward
    keyValue: profit
    type: column_aggregation
  columns:
    profit_id:
      type: integer
  relations:
    Profit:
      local: profit_id
      foreign: id
options:
  type: INNODB
  charset: utf8
  collate: utf8_general_ci