Location:
  tableName: location
  actAs:
    Blameable:
      listener: BlameableFishery
      relations:
        updated:
          class: Profile
          disabled: false
          foreign: id
        created:
          foreign: id
          disabled: false
          class: Profile
      columns:
        updated:
          type: int
          length: 4
        created:
          type: int
          length: 4
    Geographical: 
    Sluggable: 
    Timestampable: 
    Versionable: 
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      default: ''
      type: string(50)
      notnull: true
    description:
      default: ''
      type: string
      notnull: true
    depth:
      type: float
    is_free:
      type: boolean
    price:
      type: string
    location_flow_id:
      type: integer(4)
    location_fundus_id:
      type: integer(4)
    location_relief_id:
      type: integer(4)
    location_type_id:
      type: integer(4)
    location_scope_id:
      type: integer(4)
    address_id:
      type: integer(4)
  relations:
    LocationFlow:
      local: location_flow_id
      foreign: id
    LocationFundus:
      local: location_fundus_id
      foreign: id
    LocationRelief:
      local: location_relief_id
      foreign: id
    LocationType:
      local: location_type_id
      foreign: id
    LocationScope:
      local: location_scope_id
      foreign: id
    Address:
      local: address_id
      foreign: id
    Wishers:
      class: Profile
      refClass: WishList
      local: location_id
      foreign: profile_id
Profile:
  tableName: profile
  actAs:
    Timestampable: 
  columns:
    id:
      primary: true
      type: integer(4)
      notnull: true
      autoincrement: true
    nick_name:
      default: ''
      type: string(50)
      notnull: true
    first_name:
      default: ''
      type: string(50)
    last_name:
      default: ''
      type: string(50)
    birth_date:
      type: date
    userpic:
      type: string(255)
    sex:
      default: 1
      type: boolean
      notnull: true
  relations:
    Wishes:
      class: Location
      refClass: WishList
      local: profile_id
      foreign: location_id
    MyFirends:
      class: Profile
      refClass: Friend
      local: related_profile_id
      foreign: source_profile_id
    MyFirends2:
      class: Profile
      refClass: Friend
      local: source_profile_id
      foreign: related_profile_id
    Fishes:
      class: Fish
      refClass: ProfileFish
      local: profile_id
      foreign: fish_id
    Styles:
      class: Style
      refClass: ProfileStyle
      local: profile_id
      foreign: style_id
Fish:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    name:
      unique: true
      type: string(100)
      notnull: true
  relations:
    Profiles:
      class: Profile
      refClass: ProfileFish
      local: fish_id
      foreign: profile_id
Profit:
  actAs:
    Timestampable: 
    Blameable:
      listener: BlameableFishery
      columns:
        created:
          length: 4
          type: int
        updated:
          length: 4
          type: int
      relations:
        created:
          class: Profile
          disabled: false
          foreign: id
        updated:
          foreign: id
          disabled: false
          class: Profile
  columns:
    id:
      primary: true
      type: integer(4)
      notnull: true
      autoincrement: true
    location_id:
      type: integer(4)
    begin:
      type: timestamp
      notnull: true
    water_state:
      type: string
    lure:
      type: string
    bait:
      type: string
    additive:
      type: string
    weather:
      type: string
    cordage:
      type: string
    description:
      type: string
      notnull: true
  relations:
    Location:
      local: location_id
      foreign: id
Style:
  columns:
    id:
      primary: true
      type: integer
      notnull: true
      autoincrement: true
    name:
      unique: true
      type: string(100)
      notnull: true
  relations:
    Profiles:
      class: Profile
      refClass: ProfileStyle
      local: style_id
      foreign: profile_id
ProfitDetail:
  columns:
    time:
      type: timestamp
      notnull: true
    profit_id:
      type: integer(4)
    style_id:
      type: integer
    fish_id:
      type: integer
    qty:
      type: float
      notnull: true
  indexes:
    unique_fish_style_per_profit:
      fields: [profit_id, style_id, fish_id]
      type: unique
  relations:
    Profit:
      local: profit_id
      foreign: id
    Style:
      local: style_id
      foreign: id
    Fish:
      local: fish_id
      foreign: id
LocationRelief:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(50)
      notnull: true
LocationFlow:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(50)
      notnull: true
LocationFundus:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(50)
      notnull: true
Comment:
  actAs:
    Blameable:
      listener: BlameableFishery
      relations:
        created:
          class: Profile
          foreign: id
          name: CommentBy
          disabled: false
        updated:
          class: Profile
          name: ChangedBy
          foreign: id
          disabled: false
      columns:
        created:
          type: int
          length: 4
        updated:
          length: 4
          type: int
    Timestampable: 
    NestedSet:
      hasManyRoots: true
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    parent:
      type: integer(4)
    message:
      type: string(1000)
      notnull: true
CommentLocation:
  inheritance:
    extends: Comment
    type: column_aggregation
    keyField: toward
    keyValue: location
  columns:
    location_id:
      type: integer(4)
  relations:
    Location:
      local: location_id
      foreign: id
CommentProfit:
  inheritance:
    extends: Comment
    keyField: toward
    keyValue: profit
    type: column_aggregation
  columns:
    profit_id:
      type: integer(4)
  relations:
    Profit:
      local: profit_id
      foreign: id
LocationType:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      unique: true
      type: string(50)
      notnull: true
WishList:
  columns:
    profile_id:
      primary: true
      type: integer(4)
      notnull: true
    location_id:
      primary: true
      type: integer(4)
      notnull: true
  relations:
    Profile:
      local: profile_id
      foreign: id
    Location:
      local: location_id
      foreign: id
Friend:
  columns:
    source_profile_id:
      primary: true
      type: integer(4)
      notnull: true
    related_profile_id:
      primary: true
      type: integer(4)
      notnull: true
  relations:
    Profile:
      local: source_profile_id
      foreign: id
    Profile:
      local: related_profile_id
      foreign: id
Vote:
  columns:
    value:
      type: integer(4)
      notnull: true
    voter:
      type: integer(4)
  relations:
    Voter:
      class: Profile
      foreignAlias: Votes
      local: voter
      foreign: id
VoteLocation:
  inheritance:
    extends: Vote
    keyField: toward
    keyValue: location
    type: column_aggregation
  columns:
    location_id:
      type: integer(4)
  relations:
    Location:
      local: location_id
      foreign: id
VoteComment:
  inheritance:
    type: column_aggregation
    keyValue: comment
    keyField: toward
    extends: Vote
  columns:
    comment_id:
      type: integer(4)
  relations:
    Comment:
      local: comment_id
      foreign: id
VoteProfit:
  inheritance:
    type: column_aggregation
    keyValue: profit
    keyField: toward
    extends: Vote
  columns:
    profit_id:
      type: integer(4)
  relations:
    Profit:
      local: profit_id
      foreign: id
LocationScope:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      unique: true
      type: string(50)
      notnull: true
VoteProfile:
  inheritance:
    type: column_aggregation
    keyValue: profile
    keyField: toward
    extends: Vote
  columns:
    profile_id:
      type: integer(4)
  relations:
    Profile:
      local: profile_id
      foreign: id
ProfileFish:
  columns:
    fish_id:
      type: integer
      notnull: true
    profile_id:
      type: integer(4)
      notnull: true
  relations:
    Fish:
      local: fish_id
      foreign: id
    Profile:
      local: profile_id
      foreign: id
ProfileStyle:
  columns:
    style_id:
      type: integer
      notnull: true
    profile_id:
      type: integer(4)
      notnull: true
  relations:
    Style:
      local: style_id
      foreign: id
    Profile:
      local: profile_id
      foreign: id
Address:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    country:
      type: string
    administrative_area_level_1:
      type: string
    administrative_area_level_2:
      type: string
    administrative_area_level_3:
      type: string
    locality:
      type: string
options:
  type: INNODB
  charset: utf8
  collate: utf8_general_ci