options:
  type: INNODB

  
Location:
  tableName: location
  actAs:
    Geographical: ~
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(50)
      default: ''
      notnull: true
    description:
      type: string()
      default: ''
      notnull: true
    location_type_id:
      type: integer(4)
  relations:
    LocationType:
      local: location_type_id
      foreign: id
      type: one
      
LocationType:
  tableName: location_type
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(50)
      default: ''
      notnull: true
  relations:
    Location:
      local: id
      foreign: location_type_id
      type: many

Point:
  tableName: point
  actAs:
    Geographical: ~
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    route_id:
      type: integer(4)
  relations:
    Route:
      local: route_id
      foreign: id
      type: one
      onDelete: CASCADE

Route:
  tableName: route
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(50)
      default: ''
      notnull: true
    description:
      type: string()
      default: ''
      notnull: true
  relations:
    Point:
      local: id
      foreign: route_id
      type: many
